export const SET_USER_FULLNAME = 'SET_USER_FULLNAME';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_AGE = 'SET_USER_AGE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const RATE_LESSON = 'RATE_LESSON';
export const SET_LESSON_PER_DAY = 'SET_LESSON_PER_DAY';
export const SET_LESSON_START_TIME = 'SET_LESSON_START_TIME';
export const SET_SUPPORT_CYCLE = 'SET_SUPPORT_CYCLE';
